---
- name: Deploy static website to web servers
  hosts: webservers
  become: yes

  tasks:
    - name: Copy HTML, CSS, JS files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "*.html"
        - "*.css"
        - "*.js"

    - name: Copy image files
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: /var/www/html/
        owner: www-data
        group: www-data
        mode: '0644'
      with_fileglob:
        - "*.jpg"
        - "*.png"
        - "*.gif"

    - name: Restart Apache/Nginx
      ansible.builtin.service:
        name: apache2
        state: restarted